### PR TITLE
Update kit and wrangler dependencies

### PR DESCRIPTION
**Pull request by ekhaled**
Hi,

First of all, Thank you very much for this repo.
It helped us immensely in setting up our project.

This PR:
- Updates Wrangler to latest, so that it does not need the `--local` flag any more
- Updates Sveltekit and Adapter-couldflare, so that `getPlatformProxy` is used internally, and the workaround in `hooks` is not longer required
- Sets up shared Wrangler persistence storage on both workspaces
- Adds an example of a KV being shared between Sveltekit and Durable Objects

----

While this works very well...
I wonder if you can direct us towards how we can make it work with RPC calls to the DO.

Right now, any attemps to do so leads to this error:
`Error: Cannot access ``DurableObjectClass#viaRPC`` as Durable Object RPC is not yet supported between multiple ``wrangler dev`` sessions.`

If we then try to run the worker from within sveltekit's `getPlatformProxy`:
 - By adding a `main` in `sveltekit-app/wrangler.toml` pointing to the DO entry script
 - And removing `script_name` from the bindings of `sveltekit-app/wrangler.toml`

We then get this opaque error:
```
service core:user:__WRANGLER_EXTERNAL_DURABLE_OBJECTS_WORKER: Worker "core:user:__WRANGLER_EXTERNAL_DURABLE_OBJECTS_WORKER"'s binding "MY_DO" refers to a service "core:user:worker", but no such service is defined.
error when starting dev server:
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

Is it possible at all?
I know wrangler itself supports RPC, I have seen it work on normal worker/Do projects.

### CODE REVIEW

**Comment by gerhardcit** [comment]
@dario-piotrowicz , is this a PR that should be merged?
And is this the preferred way of using a DO with sveltekit still?
I remember giving up some time ago on trying to make this work in a simple way. Now that I have a need for it again I'm digging and just wondering if `wrangler dev` supports this yet if it is a sveltekit product.

**Review by dario-piotrowicz — APPROVED** [review]
@ekhaled thank you very much for the PR 🙏 

Sorry it took me so long to review it, truth be told I completely missed this and just now noticed it thanks to @gerhardcit comment 😅

The changes look great to me! thanks! 🙂

**Comment by dario-piotrowicz** [comment]
Regarding the other comments @ekhaled

>First of all, Thank you very much for this repo.
> It helped us immensely in setting up our project.

Thanks so much! I'm very glad this has been useful for you 🙏 😄 


> Right now, any attemps to do so leads to this error:
> Error: Cannot access ``DurableObjectClass#viaRPC`` as Durable Object RPC is not yet supported between multiple  ``wrangler dev`` sessions.
> ...
> Is it possible at all?
> I know wrangler itself supports RPC, I have seen it work on normal worker/Do projects.

Unfortunately wrangler does not currently support DO RPC across different workers (which is what we're doing, and we currently have to do with sveltekit), as you can see, the error you mentioned comes from wrangler itself: https://github.com/cloudflare/workers-sdk/blob/ce7db9d9cb4f5bcd5a326b86dde051cb54b999fb/packages/wrangler/src/dev/miniflare.ts#L107

> By adding a main in sveltekit-app/wrangler.toml pointing to the DO entry script
> And removing script_name from the bindings of sveltekit-app/wrangler.toml
> We then get this opaque error:
> 
>   service core:user:__WRANGLER_EXTERNAL_DURABLE_OBJECTS_WORKER: Worker  "core:user:__WRANGLER_EXTERNAL_DURABLE_OBJECTS_WORKER"'s binding "MY_DO" refers to a service 
 "core:user:worker", but no such service is defined.
> error when starting dev server:
> MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output > above.

The `main` field in the wrangler.toml is used to indicate a worker's entrypoint ([docs](https://developers.cloudflare.com/workers/wrangler/configuration/#inheritable-keys)) and that's incompatible with the output that svelteKit gives you since that is targeting Pages, so it's not really the right value to use 😕 

It should work in development but then not when you try deploying your application

I am not completely sure why it's not working to be honest 😕 

If you want please open a new issue and I'll have a look 🤔 although as I mentioned even if we made it work that would not really be super convenient either... unless we then added an additional toml file 🤔  (one for dev and one for deployments) 🤔

**Comment by dario-piotrowicz** [comment]
@gerhardcit we've just recently announced beta support for [Workers assets](https://developers.cloudflare.com/workers/static-assets/) with that full stack applications can be deployed using workers instead of pages.

For example you can use the following to create a svelteKit application and deploy it to workers:
```
npm create cloudflare@latest -- --framework=svelte --experimental
```

I'm mentioning this because in workers you can indeed define a DO in the worker itself, so now all the extra complexity and overhead we had with Pages could be completely removed.

That being said, the feature is still in `beta` (so use it at your own risk 😁), but more importantly, SvelteKit, as far as I know (please do correct me if I'm wrong) doesn't have some API/manner for us to define the DO that will be included in the worker output, we could ask the SvelteKit team if that could be implemented 🤔

That would be the cleanest/simplest solution, without that we'd have to still come up with some hacks/workarounds to make sure the generated worker includes our DO definition 🤔

**Pull request merged**
